import React from 'react';
import { AlertTriangle, ShieldAlert, CheckCircle, Activity } from 'lucide-react';
import { motion } from 'framer-motion';

const MOCK_ALERTS = [
  { id: 1, asset: 'Turbine Generator A', severity: 'critical', type: 'Vibration Anomaly', time: '10 mins ago', status: 'active', desc: 'Bearing vibration exceeded 15mm/s limit. Immediate inspection required.' },
  { id: 2, asset: 'Hydraulic Press HP-01', severity: 'high', type: 'Temperature Spike', time: '1 hour ago', status: 'investigating', desc: 'Hydraulic fluid temp reached 85°C. Cooling system check recommended.' },
  { id: 3, asset: 'Conveyor Belt System 2', severity: 'medium', type: 'Motor Load', time: '3 hours ago', status: 'resolved', desc: 'Transient load spike detected. Normal operation resumed.' }
];

export default function AnomalyFeed() {
  return (
    <div className="space-y-8 max-w-5xl mx-auto">
      <div className="flex justify-between items-center bg-gray-900/40 p-6 rounded-2xl border border-gray-800 backdrop-blur-sm">
        <div className="flex items-center space-x-4">
          <div className="p-3 bg-red-500/20 rounded-xl border border-red-500/30 shadow-[0_0_15px_rgba(239,68,68,0.2)]">
            <Activity className="w-8 h-8 text-red-500" />
          </div>
          <div>
            <h1 className="text-3xl font-mono font-bold text-white tracking-wide">Anomaly Feed</h1>
            <p className="text-gray-400 mt-1 text-sm">Real-time alerts and predictive maintenance triggers generated by AI.</p>
          </div>
        </div>
      </div>

      <div className="grid gap-6">
        {MOCK_ALERTS.map((alert, i) => (
          <motion.div 
            key={alert.id}
            initial={{ opacity: 0, x: -20, rotateX: 10 }}
            animate={{ opacity: 1, x: 0, rotateX: 0 }}
            transition={{ delay: i * 0.15, type: "spring", stiffness: 100 }}
            className={`p-6 rounded-xl border shadow-lg backdrop-blur-md transition-all hover:scale-[1.01] ${
              alert.severity === 'critical' ? 'bg-gray-900/80 border-red-500/40 shadow-[0_0_20px_rgba(239,68,68,0.15)]' :
              alert.severity === 'high' ? 'bg-gray-900/60 border-orange-500/30' :
              'bg-gray-900/40 border-gray-800'
            }`}
          >
            <div className="flex justify-between items-start">
              <div className="flex space-x-5">
                <div className={`p-4 rounded-2xl shrink-0 border ${
                  alert.severity === 'critical' ? 'bg-red-500/20 text-red-400 border-red-500/50 shadow-[0_0_15px_rgba(239,68,68,0.4)] animate-pulse-slow' :
                  alert.severity === 'high' ? 'bg-orange-500/20 text-orange-400 border-orange-500/30' :
                  'bg-yellow-500/10 text-yellow-500 border-yellow-500/20'
                }`}>
                  {alert.severity === 'critical' ? <ShieldAlert className="w-7 h-7" /> : <AlertTriangle className="w-7 h-7" />}
                </div>
                <div>
                  <div className="flex items-center space-x-3 mb-1">
                    <h3 className="text-xl font-bold text-white tracking-wide">{alert.type}</h3>
                    <span className="text-sm font-mono text-accent bg-accent/10 px-2 py-0.5 rounded border border-accent/20">{alert.time}</span>
                  </div>
                  <p className="text-gray-300 font-medium text-sm flex items-center mb-3">
                    <span className="text-gray-500 mr-2">Asset Target:</span> {alert.asset}
                  </p>
                  <p className="text-gray-400 text-sm leading-relaxed max-w-2xl">{alert.desc}</p>
                </div>
              </div>
              <div>
                <span className={`inline-flex items-center px-4 py-1.5 rounded-full text-xs font-bold uppercase tracking-widest border ${
                  alert.status === 'active' ? 'bg-red-500 text-white border-red-400 shadow-[0_0_15px_rgba(239,68,68,0.6)]' :
                  alert.status === 'investigating' ? 'bg-blue-500/20 text-blue-400 border-blue-500/50' :
                  'bg-green-500/10 text-green-400 border-green-500/30'
                }`}>
                  {alert.status === 'resolved' && <CheckCircle className="w-4 h-4 mr-1.5" />}
                  {alert.status}
                </span>
              </div>
            </div>
            
            {alert.status !== 'resolved' && (
              <div className="mt-6 pt-5 border-t border-gray-800 flex justify-end space-x-4">
                <button className="px-5 py-2.5 text-sm font-bold text-gray-300 bg-gray-800 hover:bg-gray-700 hover:text-white rounded-lg transition-all border border-gray-700">
                  Acknowledge
                </button>
                <button className="px-5 py-2.5 text-sm font-bold text-gray-900 bg-accent hover:bg-white rounded-lg transition-all shadow-[0_0_15px_rgba(6,182,212,0.4)] hover:shadow-[0_0_20px_rgba(255,255,255,0.6)]">
                  Generate Remediation Plan
                </button>
              </div>
            )}
          </motion.div>
        ))}
      </div>
    </div>
  );
}
